# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_maker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts_made', to='users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts_received', to='users.User'),
            preserve_default=False,
        ),
    ]
