# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
